#Created by JInto - www.guh-software.de
#Thu May 18 14:00:50 CEST 2017
iatrix.WebBrowserView=Web Browser
iatrix.commands.category=Iatrix
iatrix.commands.export_clipboard=Export to Clipboard
iatrix.commands.newcons=New Consultation
iatrix.commands.newproblem=New Problem
iatrix.commands.send_email=Send Email
iatrix.commands.show_all_consultations=Show all consultations
iatrix.commands.show_more_consultations=Show more consultations
iatrix.iatrix.perspective=Iatrix perspective
iatrix.perspective=
iatrix.view.context.name=Iatrix
iatrix.view.konslist.context.name=Iatrix Consultations
